# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PiPoutch/github-actions-ci
    rev: v2.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
